# -*- coding: utf-8 -*-
"""29th sept assignment solved.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHIFipjOsEaZmr5nzVPde1r33K1_86Ul

1. write a function which will try to find out len of a string without using an inbuilt len function
"""

#ans1
def length(name):
  tot=0
  for i in name:
    tot=tot+1
  return tot

length("happy")

"""2. write a function which  will be able to print an index of list element without using an index function"""

#Ans2
lst=[2,3,4,1]
def indx(lst,x):
  i=-1
  for num in lst:
    i=i+1
    if num==x:
      print(i)
      break

lst=[2,3,4,1]
indx(lst,1)

"""5. write a function which will take input as a list with any kind of numeric value and give an out as a multiplication of 
all the numeric data l = [3.5, 6.56, 4,5,"sudh" , "ineuron" , 'fsda bootcamp 2.0']
"""

#Ans5)
l = [3.5, 6.56, 4,5,"sudh" , "ineuron" , 'fsda bootcamp 2.0']

def test(lst):
  new_list=[]
  product=1
  for i in lst:
    if type(i)==int or type(i)==float:
      new_list.append(i)
      product=product*i
  return product

test([3.5, 6.56, 4,5,"sudh" , "ineuron" , 'fsda bootcamp 2.0'])

"""3. write a function which will be able to print an ip address of your system"""

import socket
def IPaddress():
  hostname = socket.gethostname()
  IPAddr = socket.gethostbyname(hostname)
  return "Your Computer IP Address is:" + IPAddr

IPaddress()

"""4. write a function which will shutdown your system"""

import os
def shutdown():
  os.system("shutdown /s /t 1")

shutdown()